add_lunch_combo crimson_mako-userdebug
add_lunch_combo crimson_find5-userdebug
add_lunch_combo crimson_hercules-userdebug
add_lunch_combo crimson_m7att-userdebug
add_lunch_combo crimson_m7spr-userdebug
add_lunch_combo crimson_m7tmo-userdebug
add_lunch_combo crimson_m7ul-userdebug
add_lunch_combo crimson_vibrantmtd-userdebug
